### ISSUE TITLE
Never goes to sleep, causing higher-than-necessary power consumption.

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/mbed-6lowpan-eventloop-adaptor#13]
There's a big TODO where there should be a nice low-power sleep: https://github.com/ARMmbed/mbed-6lowpan-eventloop-adaptor/blob/master/source/events.cpp#L65

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-2122

**Comment by artokin** [comment]
mbed-6lowpan-eventloop-adaptor contains unnecessary implementation of _wait and _sleep, those methods are not needed in mbed OS port and they are removed in commit 7e10821b247329cda9e3e9a6e28012b64587b9f8.
