### ISSUE TITLE
platform_enter_critical and platform_exit_critical implementations are not atomic

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/mbed-6lowpan-eventloop-adaptor#15]
The increment and decrement operators used are not re-entrant, a re-entrant call from an interrupt handler may cause an incorrect value to be stored depending on how these functions are used. The implementation should probably use ldrex/strex like the core-util CriticalSectionLock does: https://github.com/ARMmbed/core-util/blob/master/core-util/CriticalSectionLock.h

Even in that case it should be carefully considered whether this is interoperable with using CriticalSectionLock elsewhere in the program.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-2120

**Comment by kjbracey-arm** [comment]
I don't like the look of this API either - clearly the "enter" should return a previous state to pass to the leave function.

However, I can't see how it's not safe in mbed OS. An interrupt routine can't net change the counter value in the middle of the foreground increment - it might call enter/exit, but that leaves the counter value the same.

I see some platforms have the alternate enter implementation

    disable_irq()
    counter++;

which does look nicer. Maybe just change it to that?

On inspecting it though, I'm now worried about interrupt routines calling enter/exit, and ending up with interrupts enabled.

**Comment by autopulated** [comment]
Yeah we noticed that even our CriticalSection implementation in mbed OS could break if an interrupt handler leaves interrupts disabled after returning. There's no atomic way of reading the interrupt state, so as far as I understand the only way to fix that is to either document the limitation on interrupt handlers, or have a single API that everyone must use to enable/disable interrupts which separately atomically tracks the state.

Would the best way to fix this to provide a C API for CriticalSectionLock which declares that its enter/exit functions must always be used in matched pairs, and to not do so is an error?

**Comment by kjbracey-arm** [comment]
An interrupt handler that changed foreground interrupt mask state would be fundamentally broken, surely? Trying to imagine why you would ever allow that. It would be as weird as changing foreground registers.

But certainly in principle the mbed OS port of Nanostack should be using OS functions for this stuff rather than trying to do it itself - so if you could provide a C API, that could happen.

**Comment by kjbracey-arm** [comment]
Just to clarify - my concern in our implementation is

  IRQ entry (IRQs disabled)
  run with IRQs disabled as expected
  enter_critical (counter:=1)
  leave_critical (counter:=0, IRQs enabled)
  run with IRQs enabled!
  IRQ exit

I seem to recall a quiet "increment counter by 1 on IRQ entry" to avoid this, but now I can't find it...

**Comment by SeppoTakalo** [comment]
With the given API, it is not possible to fix this.
