### ISSUE TITLE
Requires old version of mbed-drivers 0.12.0 

### ISSUE THREAD

**Issue by kmdewaal** [ARMmbed/mbed-6lowpan-eventloop-adaptor#19]
This module requires an old version of the mbed-drivers, 0.12.0.
This gives a compilation error when used with the latest mbed-drivers:

> yotta -t frdm-k64f-gcc build 
> error: mbed-drivers does not meet specification ~0.12.0 required by mbed-6lowpan-eventloop-adaptor
>

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2462

**Comment by SeppoTakalo** [comment]
Fixed in v1.1.1
